# Site settings
title: 暁の履歴書
description: 暁の履歴書
favicon: /assets/img/avatar.JPG
baseurl: 
url: https://github.com/blaspheme/blaspheme.github.io
rss_url: /pages/atom.xml
google_analytics: 

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 王晓
  title: 算法工程师&架构
  address: Tokyo, Japan
  email: mooncrime93@gmail.com
  link: 
  weibo:
  github: blaspheme
  linkedin: 
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work3:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work1:
      company: 全球海运系统
      location: 厦门, 中国
      title: 厦门吉联科技有限公司
      started: 2016
      duration: (2016.7 - 2017.3)
      description: 主要负责使用Java，完成原生GUI和后端Web服务的开发，
  companyHistory:
    - company3:
      company: 南京新智感信息科技有限公司
      location: 南京, 中国
      title: 架构师
      started: 2020
      duration: (2020.9 - 2022.3)
      description: 期间主要从事架构职位：①RPA(UiBot)实践;②Cloud Native实践;③DevOps体系的培训与实践;④SpringBoot(RESTFul、SOAP)系统构建
    - company2:
      company: 南京中孚信息技术有限公司
      location: 南京, 中国
      title: 算法工程师
      started: 2017
      duration: (2017.3 - 2020.3)
      description: 期间从事算法开发：①贝叶斯概率论(DNN)的研究和实现;②Semantic Network、NLP的研究与实现;③图数据库与图算法的研究与实现;④其他的各类算法实现
    - company1:
      company: 厦门吉联科技有限公司
      location: 厦门, 中国
      title: Java Developer
      started: 2016
      duration: (2016.7 - 2017.3)
      description: 期间主要使用的技术栈：①OSGI+JFace+RCP3.x(Eclipse)开发原生桌面端;②Spring+Struts2+Hibernate后台开发;③Oracle使用;④Maven、WebLogic、VBA等各类工具使用
  educationHistory:
    - education1:
      organization: 集美大学诚毅学院
      location: 厦门, 中国
      degree: Bachelor(学士)
      major: Software Engineering(软件工程)
      started: 2012
      duration: (2012 - 2016)
      description: 
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  patent:
    - patent1:
      name: 专利1
  programmingSkills:
    - skill1:
      name: AI&ML
      percentage: 80%
    - skill2:
      name: 概率论&统计学
      percentage: 80%
    - skill3:
      name: 操作系统
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Vue
      percentage: 90%
