# Site settings
title: 暁の履歴書
description: 暁の履歴書
favicon: /assets/img/avatar.JPG
baseurl: 
url: https://github.com/blaspheme/blaspheme.github.io
rss_url: /pages/atom.xml
google_analytics: 

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 王晓
  title: 算法工程师&架构师
  address: Tokyo, Japan
  email: mooncrime93@gmail.com
  link: 
  weibo:
  github: blaspheme
  linkedin: 
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work6:
      company: 国家电网ERP系统
      location: 南京, 中国
      title: 南京新智感信息科技有限公司
      started: 2021
      duration: (2021.3 - 2022.3)
      description: 搭建SpringBoot微服务架构（权限模型构建，行级数据权限分配），Apache CXF使用SOAP完成系统间数据交互，服务器配置(RAID、LVM、NetworkManager等)
    - work5:
      company: RPA/自动化测试实施
      location: 南京, 中国
      title: 南京新智感信息科技有限公司
      started: 2020
      duration: (2020.9 - 2021.3)
      description: 使用UiBot、Gauge(TDD)+Puppeteer/Taiko、Robot Framework+Selenium 搭建RPA/自动化测试系统，补全DevOps验收环节；Gitlab+Gitlab runner+git flow定义软件开发环节
    - work4:
      company: 语义网(知识图谱)推理系统
      location: 南京, 中国
      title: 南京中孚信息技术有限公司
      started: 2019
      duration: (2019.1 - 2020.3)
      description: 结合拓扑学，完成对一阶逻辑谓词(Prolog,Datalog)的实现，为了性能劣化为Semantic Network，期间预研(CiteSpace、Semantic MediaWiki、Wikibase等系统)，使用SPARQL对RDF数据查询，OWL结合本体论对数据定义
    - work3:
      company: 数据(情报)预测
      location: 南京, 中国
      title: 南京中孚信息技术有限公司
      started: 2018
      duration: (2018.1 - 2019.1)
      description: 信念网络模型建立，完成对未来的预测，期间预研过多种技术：Bayes Server、GaussDB、Bayeslite等概率型结构实现与原理；
    - work2:
      company: 南京GA数据分析
      location: 南京, 中国
      title: 南京中孚信息技术有限公司
      started: 2017
      duration: (2017.3 - 2018.1)
      description: 实现关联分析(FP-growth等)、聚类分析(DBSCAN等)等非监督学习方法完成对数据分析，找到关系数据，以及对数据进行线性拟合，建立适当模型(时序模型)完成对未来的预测；图数据库的详细分析（分享链接:https://www.jianshu.com/p/38b70768380c）
    - work1:
      company: 全球海运系统
      location: 厦门, 中国
      title: 厦门吉联科技有限公司
      started: 2016
      duration: (2016.7 - 2017.3)
      description: 主要负责使用Java，完成原生GUI和后端Web服务的开发，在职期间写过8000多行的Oracle的存储过程
  companyHistory:
    - company3:
      company: 南京新智感信息科技有限公司
      location: 南京, 中国
      title: 架构师
      started: 2020
      duration: (2020.9 - 2022.3)
      description: 期间主要从事架构职位：①RPA(UiBot)实践;②Cloud Native实践;③DevOps体系的培训与实践;④SpringBoot(RESTFul、SOAP)系统构建
    - company2:
      company: 南京中孚信息技术有限公司
      location: 南京, 中国
      title: 算法工程师
      started: 2017
      duration: (2017.3 - 2020.3)
      description: 期间从事算法开发：①贝叶斯概率论(DNN)的研究和实现;②Semantic Network、NLP的研究与实现;③图数据库与图算法的研究与实现;④其他的各类算法实现
    - company1:
      company: 厦门吉联科技有限公司
      location: 厦门, 中国
      title: Java Developer
      started: 2016
      duration: (2016.7 - 2017.3)
      description: 期间主要使用的技术栈：①OSGI+JFace+RCP3.x(Eclipse)开发原生桌面端;②Spring+Struts2+Hibernate后台开发;③Oracle使用;④Maven、WebLogic、VBA等各类工具使用
  educationHistory:
    - education1:
      organization: 集美大学诚毅学院
      location: 厦门, 中国
      degree: Bachelor(学士)
      major: Software Engineering(软件工程)
      started: 2012
      duration: (2012 - 2016)
      description: 
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: 四级
    - language3:
      name: Japanese
      proficiency: N5
  award:
    - award1:
      name: 全国大学生数学建模比赛国家一等奖
  patent:
    - patent1:
      name: 201710782155.9(申请号)
    - patent2:
      name: 201810953598.4(申请号)
    - patent3:
      name: PA18042089(方案号)
    - patent4:
      name: 201811276062.X(申请号)
    - patent5:
      name: PA19015796(方案号)
  programmingSkills:
    - skill1:
      name: AI&ML
      percentage: 80%
    - skill3:
      name: 操作系统
      percentage: 70%
    - skill4:
      name: Cloud Native
      percentage: 70%
    - skill5:
      name: DevOps
      percentage: 70%
    - skill6:
      name: Web开发
      percentage: 70%
    - skill7:
      name: GUI开发
      percentage: 70%
    - skill2:
      name: 概率论&统计学
      percentage: 80%